birth: 1985-08-10
attributes:
- name:
    zh-cn: 力量
    en-us: STR
    ja-jp: ちから
  value: 2000
- name:
    zh-cn: 耐力
    en-us: VIT
    ja-jp: たいりょく
  value: 3000
- name:
    zh-cn: 智力
    en-us: INT
    ja-jp: ちえ
  value: 5000
- name:
    zh-cn: 意志
    en-us: SPI
    ja-jp: せいしん
  value: 5000
- name:
    zh-cn: 敏捷
    en-us: AGI
    ja-jp: きびん
  value: 1000
- name:
    zh-cn: 幸运
    en-us: LUC
    ja-jp: うん
  value: 9999
jobs:
- name:
    zh-cn: 软件工程师
    en-us: Software Engineer
    ja-jp: ソフトウェアエンジニア
  scope: software
  attributes:
  - name:
      zh-cn: 计算机体系结构
      en-us: Computer Architecture
    value: 5
  - name:
      zh-cn: 操作系统
      en-us: Operating System
    value: 100
  - name:
      zh-cn: 编程语言
      en-us: Programming Language
    value: 500
  - name:
      zh-cn: 算法与数据结构
      en-us: Algorithms & Data Structures
    value: 100
  - name:
      zh-cn: 软件设计
      en-us: Software Design
    value: 500
  - name:
      zh-cn: 软件工程
      en-us: Software Engineering
    value: 500
- name:
    zh-cn: 阿宅
    en-us: OTAKU
    ja-jp: オタク
  scope: otaku
  attributes:
  - name:
      zh-cn: 动画
      en-us: Animation
      ja-jp: アニメーション
    value: 5000
  - name:
      zh-cn: 漫画
      en-us: Comics
      ja-jp: コミックス
    value: 1000
  - name:
      zh-cn: 游戏
      en-us: Game
      ja-jp: ゲーム
    value: 7000
  - name:
      zh-cn: 小说
      en-us: Novel
      ja-jp: ノベル
    value: 1000
  - name:
      zh-cn: 模型
      en-us: Figure
      ja-jp: フィギュア
    value: 0
  - name:
      zh-cn: 角色扮演
      en-us: Cosplay
      ja-jp: コスプレ
    value: 0
- name:
    zh-cn: 化学家
    en-us: Chemist
    ja-jp: 化学者
  scope: chemistry
  attributes:
  - name:
      zh-cn: 无机化学
      en-us: Inorganic Chemistry
      ja-jp: 無機化学
    value: 100
  - name:
      zh-cn: 有机化学
      en-us: Organic Chemistry
      ja-jp: 有機化学
    value: 5
  - name:
      zh-cn: 物理化学
      en-us: Physical Chemistry
      ja-jp: 物理化学
    value: 200
  - name:
      zh-cn: 分析化学
      en-us: Analytical Chemistry
      ja-jp: 分析化学
    value: 200
  - name:
      zh-cn: 计算化学
      en-us: Computational Chemistry
      ja-jp: 計算化学
    value: 0
  - name:
      zh-cn: 生物化学
      en-us: Biochemistry
      ja-jp: 生化学
    value: 0
skills:
- name:
    zh-cn: 英语
    en-us: English
    ja-jp: 英語
  scopes:
  - common
  - language
  icon: chat
  progress: 0.4
- name:
    zh-cn: 日语
    en-us: Japanese
    ja-jp: 日本語
  scopes:
  - common
  - language
  - otaku
  icon: chat
  progress: 0.4
- name:
    zh-cn: JavaScript
    en-us: JavaScript
    ja-jp: JavaScript
  scopes:
  - software
  - programming language
  icon:
  progress: 0.6
- name:
    zh-cn: Node.js
    en-us: Node.js
    ja-jp: Node.js
  scopes:
  - software
  - runtime
  icon:
  progress: 0.4
- name:
    zh-cn: C#
    en-us: C#
    ja-jp: C#
  scopes:
  - software
  - programming language
  icon:
  progress: 0.2
- name:
    zh-cn: .NET
    en-us: .NET
    ja-jp: .NET
  scopes:
  - software
  - runtime
  icon:
  progress: 0.1
- name:
    zh-cn: Java
    en-us: Java
    ja-jp: Java
  scopes:
  - software
  - programming language
  icon:
  progress: 0.2
- name:
    zh-cn: DevOps
    en-us: DevOps
    ja-jp: DevOps
  scopes:
  - software
  - methodology
  icon:
  progress: 0.3
- name:
    zh-cn: Kubernetes
    en-us: Kubernetes
    ja-jp: Kubernetes
  scopes:
  - software
  - platform
  icon:
  progress: 0.4
- name:
    zh-cn: AWS
    en-us: AWS
    ja-jp: AWS
  scopes:
  - software
  - platform
  icon:
  progress: 0.3
- name:
    zh-cn: 研究
    en-us: Research
    ja-jp: 研究
  scopes:
  - common
  - chemistry
  icon:
  progress: 0.5
- name:
    zh-cn: 实验
    en-us: Experiment
    ja-jp: 実験
  scopes:
  - chemistry
  icon:
  progress: 0.1
- name:
    zh-cn: 报告
    en-us: Report
    ja-jp: 報告
  scopes:
  - common
  - chemistry
  icon:
  progress: 0.2
achievements:
- name:
    zh-cn: 计算机技术与软件专业技术资格 中级 软件设计师
    en-us: Software Designer, Qualification of Computer and Software Professional
  date: 2017-05-20
- name:
    zh-cn: 会计从业资格证书
    en-us: Certificate of Accounting Profession
  date: 2017-02-14
- name:
    zh-cn: 日本语能力测试1级
    en-us: Japanese-Language Proficiency Test Level 1
    ja-jp: 日本語能力試験1級
  date: 2009-08-28
- name:
    zh-cn: 北京化工大学应用化学理学学士
    en-us: Bachelor, Applied Chemistry, BUCT
  date: 2008-07-02
- name:
    zh-cn: 大学英语四级考试
    en-us: CET4
  date: 2006-06-01
