name: gh-pages
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
      NODE_ENV: production
      PUBLISH_BRANCH: master
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node
      - name: build
        run: npm ci && npm run build
      - uses: peaceiris/actions-gh-pages@v3.4.0
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
          publish_branch: ${{ env.PUBLISH_BRANCH }}
          user_name: James Ren
          user_email: renshujian0@hotmail.com
          commit_message: ${{ github.event.head_commit.message }}
      - name: mirror
        env:
          GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
        run: |
          ls -RI *module* $HOME $GITHUB_WORKSPACE
          cd $(find $HOME -name actions_github_pages* -type d)
          git push git@e.coding.net:booksword/online.git ${{ env.PUBLISH_BRANCH }}:master
